[package]
name = "binpack_rs"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "binpack_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
rand = "0.9.1"
